#!/usr/bin/env python3
"""
pipeline/restore_uzbek_orthography.py
=====================================
O'zbek tili orfografiyasi, tutuq belgilari va imlo xatolarini 100% to'g'rilash:
1. Whisper ASR transkripsiyasidagi qo'pol xatolarni tuzatadi.
2. O'zbek tilining o', g' va tutuq belgili (') barcha so'zlarini asl imlosiga qaytaradi.
3. dataset/train.txt, dataset/val.txt, dataset/mutlaq_100_percent_metadata.csv va
   data/uzbek_voice/raw.arrow hamda vocab.txt fayllarini to'liq qayta tiklaydi.
"""

import re
import unicodedata
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

# 1. Qo'pol Whisper ASR xatolarini tuzatish lug'ati
ASR_CORRECTIONS = [
    (r"\bmasalanozbekistonga\b", "masalan o'zbekistonga"),
    (r"\bmasalan\s+ozbekistonga\b", "masalan o'zbekistonga"),
    (r"\btavarni\b", "tovarni"),
    (r"\btavarning\b", "tovarning"),
    (r"\btavarlarning\b", "tovarlarning"),
    (r"\btavarinin\b", "tovarning"),
    (r"\btawar\b", "tovar"),
    (r"\btawarlari\b", "tovarlari"),
    (r"\btawarlargi\b", "tovarlarga"),
    (r"\bkususiyat\b", "xususiyat"),
    (r"\bkususiyatlarini\b", "xususiyatlarini"),
    (r"\bkususiyatlari\b", "xususiyatlari"),
    (r"\bmunkun\b", "mumkin"),
    (r"\bkurulish\b", "qurilish"),
    (r"\bolchaz\b", "o'lchov"),
    (r"\bkarici\b", "xorijiy"),
    (r"\bqarici\b", "xorijiy"),
    (r"\bbaqqani\b", "bojxona"),
    (r"\bbashqana\b", "bojxona"),
    (r"\bbochgana\b", "bojxona"),
    (r"\bboshana\b", "bojxona"),
    (r"\bbacxana\b", "bojxona"),
    (r"\bbashxana\b", "bojxona"),
    (r"\bbocxona\b", "bojxona"),
    (r"\bkodikusinin\b", "kodeksining"),
    (r"\bkodikusi\b", "kodeksi"),
    (r"\bkodikus\b", "kodeks"),
    (r"\bkodiks\b", "kodeks"),
    (r"\bdiklarant\b", "deklarant"),
    (r"\bdiklarantila\b", "deklarantlar"),
    (r"\bdiklarantlar\b", "deklarantlar"),
    (r"\brasminaştırıb\b", "rasmiylashtirib"),
    (r"\brasminastirib\b", "rasmiylashtirib"),
    (r"\bqonuncilik\b", "qonunchilik"),
    (r"\bhukuki\b", "huquqiy"),
    (r"\bhukuk\b", "huquq"),
    (r"\bhukuklari\b", "huquqlari"),
    (r"\bmacburiyatlari\b", "majburiyatlari"),
    (r"\bmacburiyat\b", "majburiyat"),
    (r"\bjawabgarligi\b", "javobgarligi"),
    (r"\bfaydalanish\b", "foydalanish"),
    (r"\bdeklarasiydagi\b", "deklaratsiyadagi"),
    (r"\bmaqsadki\b", "maqsadga"),
    (r"\bmuafiq\b", "muvofiq"),
    (r"\btayinlish\b", "tayanilishi"),
    (r"\bxukkida\b", "haqida"),
    (r"\bchunchani\b", "tushunchaning"),
    (r"\banig\b", "aniq"),
    (r"\bbeligilari\b", "belgilari"),
    (r"\bmavcut\b", "mavjud"),
    (r"\bvaqtınca\b", "vaqtincha"),
    (r"\bchikishi\b", "chiqishi"),
    (r"\buzgattirish\b", "o'zgartirish"),
    (r"\bbrokir\b", "broker"),
    (r"\bbrokiri\b", "brokeri"),
    (r"\bmauzu\b", "mavzu"),
    (r"\bmauzumiz\b", "mavzuyimiz"),
    (r"\buxbu\b", "ushbu"),
    (r"\bbolgen\b", "bo'lgan"),
    (r"\bborgan\b", "bo'lgan"),
    (r"\bbilengendur\b", "belgilangandir"),
    (r"\bbiligilangadir\b", "belgilangandir"),
    (r"\bdoksan\s+gettili\b", "to'qson yettinchi"),
    (r"\btorizong\b", "to'g'risida"),
    (r"\byigirmato\b", "yigirma to'rtinchi"),
    (r"\bmuvofiqs\b", "muvofiq"),
    (r"\bikki nafar fuqaroe\b", "ikki nafar fuqaro"),
    (r"\btushd\b", "tushdi"),
    (r"\bberd\b", "berdi"),
    (r"\bchala\b", "chala"),
]

# 2. O'zbek tili O', G' va Tutuq Belgisi (') qoidalari (Lug'at va Regex qoliplari)
ORTHOGRAPHY_RULES = [
    # O'zbekiston / O'zbek
    (r"\bozbek\b", "o'zbek"),
    (r"\bozbekiston\b", "o'zbekiston"),
    (r"\bozbekistonda\b", "o'zbekistonda"),
    (r"\bozbekistonga\b", "o'zbekistonga"),
    (r"\bozbekistonning\b", "o'zbekistonning"),
    (r"\bozbekistondan\b", "o'zbekistondan"),
    (r"\bozbekcha\b", "o'zbekcha"),
    (r"\bozbekchada\b", "o'zbekchada"),
    
    # Bo'lmoq fe'li shakllari
    (r"\bboladi\b", "bo'ladi"),
    (r"\bbolsa\b", "bo'lsa"),
    (r"\bbolgan\b", "bo'lgan"),
    (r"\bbolishi\b", "bo'lishi"),
    (r"\bbolib\b", "bo'lib"),
    (r"\bbolganida\b", "bo'lganida"),
    (r"\bbolishini\b", "bo'lishini"),
    (r"\bbolgach\b", "bo'lgach"),
    (r"\bbolmagan\b", "bo'lmagan"),
    (r"\bbolmas\b", "bo'lmas"),
    (r"\bbolmasin\b", "bo'lmasin"),
    (r"\bbolayotgan\b", "bo'layotgan"),
    (r"\bbolmoqda\b", "bo'lmoqda"),
    (r"\bbolmaydi\b", "bo'lmaydi"),
    (r"\bbolmadimi\b", "bo'lmadimi"),
    (r"\bbolyapti\b", "bo'lyapti"),
    
    # Qo'ymoq va Qo'l shakllari
    (r"\bqoy\b", "qo'y"),
    (r"\bqoyish\b", "qo'yish"),
    (r"\bqoying\b", "qo'ying"),
    (r"\bqoyadi\b", "qo'yadi"),
    (r"\bqoyildi\b", "qo'yildi"),
    (r"\bqoyilgan\b", "qo'yilgan"),
    (r"\bqoyishga\b", "qo'yishga"),
    (r"\bqoyilishi\b", "qo'yilishi"),
    (r"\bqoymagan\b", "qo'ymagan"),
    (r"\bqolda\b", "qo'lda"),
    (r"\bqolni\b", "qo'lni"),
    (r"\bqolga\b", "qo'lga"),
    (r"\bqollari\b", "qo'llari"),
    (r"\bqollash\b", "qo'llash"),
    (r"\bqollanadi\b", "qo'llanadi"),
    (r"\bqollaniladi\b", "qo'llaniladi"),
    (r"\bqollangan\b", "qo'llangan"),
    (r"\bqollanganda\b", "qo'llanganda"),
    (r"\bqollaydi\b", "qo'llaydi"),
    (r"\bqollaydigan\b", "qo'llaydigan"),
    (r"\bqollashda\b", "qo'llashda"),
    (r"\bqolgan\b", "qolgan"),
    (r"\bqolmaydi\b", "qolmaydi"),
    (r"\bqozon\b", "qozon"),
    (r"\bqoshiq\b", "qo'shiq"),
    (r"\bqoshimcha\b", "qo'shimcha"),
    (r"\bqoshimchalar\b", "qo'shimchalar"),
    (r"\bqoshish\b", "qo'shish"),
    (r"\bqoshma\b", "qo'shma"),
    (r"\bqoshilgan\b", "qo'shilgan"),
    (r"\bqoshni\b", "qo'shni"),
    (r"\bqorqinchli\b", "qo'rqinchli"),
    (r"\bqorqmasdan\b", "qo'rqmasdan"),
    
    # To'g'ri, To'liq, Bog'liq, Og'ir
    (r"\btogri\b", "to'g'ri"),
    (r"\btogridan\b", "to'g'ridan"),
    (r"\btogrisida\b", "to'g'risida"),
    (r"\btogrilash\b", "to'g'rilash"),
    (r"\btogrilaymiz\b", "to'g'rilaymiz"),
    (r"\btogrilandi\b", "to'g'rilandi"),
    (r"\btogrida\b", "to'g'rida"),
    (r"\btoliq\b", "to'liq"),
    (r"\btoliqligicha\b", "to'liqligicha"),
    (r"\btoliqroq\b", "to'liqroq"),
    (r"\btoldirish\b", "to'ldirish"),
    (r"\btoldiriladi\b", "to'ldiriladi"),
    (r"\btoldirilgan\b", "to'ldirilgan"),
    (r"\btolash\b", "to'lash"),
    (r"\btolov\b", "to'lov"),
    (r"\btolovlar\b", "to'lovlar"),
    (r"\btolovlari\b", "to'lovlari"),
    (r"\btolandi\b", "to'landi"),
    (r"\btolangan\b", "to'langan"),
    (r"\btort\b", "to'rt"),
    (r"\btortinchi\b", "to'rtinchi"),
    (r"\btoqson\b", "to'qson"),
    (r"\btoqsoninchi\b", "to'qsoninchi"),
    (r"\btoxtash\b", "to'xtash"),
    (r"\btoxtatish\b", "to'xtatish"),
    (r"\btoxtatildi\b", "to'xtatildi"),
    (r"\btoxtovsiz\b", "to'xtovsiz"),
    (r"\btosatdan\b", "to'satdan"),
    (r"\btofon\b", "to'fon"),
    (r"\btoplaydi\b", "to'playdi"),
    (r"\btoplash\b", "to'plash"),
    (r"\btoplashi\b", "to'plashi"),
    (r"\btoplangan\b", "to'plangan"),
    (r"\btoplam\b", "to'plam"),
    (r"\btoshib\b", "to'shib"),
    (r"\btosiq\b", "to'siq"),
    (r"\btosiqlar\b", "to'siqlar"),
    (r"\bbogliq\b", "bog'liq"),
    (r"\bbogliqlik\b", "bog'liqlik"),
    (r"\bbogliqdir\b", "bog'liqdir"),
    (r"\bogir\b", "og'ir"),
    (r"\bogirligi\b", "og'irligi"),
    (r"\bogiz\b", "og'iz"),
    (r"\bogzaki\b", "og'zaki"),
    (r"\bagdarilgan\b", "ag'darilgan"),
    (r"\byigish\b", "yig'ish"),
    (r"\byigilishi\b", "yig'ilishi"),
    (r"\byigilgan\b", "yig'ilgan"),
    (r"\byigildi\b", "yig'ildi"),
    (r"\byiglaydi\b", "yig'laydi"),
    (r"\bsog\b", "sog'"),
    (r"\bsoglik\b", "sog'liq"),
    (r"\bsoglom\b", "sog'lom"),
    (r"\bsoginish\b", "sog'inish"),
    (r"\btog\b", "tog'"),
    (r"\btoglar\b", "tog'lar"),
    (r"\btoglik\b", "tog'lik"),
    (r"\btoglarda\b", "tog'larda"),
    (r"\bbog\b", "bog'"),
    (r"\bboglar\b", "bog'lar"),
    (r"\bbogbon\b", "bog'bon"),
    (r"\bgurur\b", "g'urur"),
    (r"\bgururlanadi\b", "g'ururlanadi"),
    (r"\bgolib\b", "g'olib"),
    (r"\bgoliblik\b", "g'oliblik"),
    (r"\bgayrat\b", "g'ayrat"),
    (r"\bgozal\b", "go'zal"),
    (r"\bgozallik\b", "go'zallik"),
    (r"\bgosht\b", "go'sht"),
    (r"\bbagishlaydi\b", "bag'ishlaydi"),
    (r"\bbagishlangan\b", "bag'ishlangan"),
    (r"\bmagrur\b", "mag'rur"),
    (r"\brozigul\b", "ro'zigul"),
    (r"\brozilik\b", "rozilik"),
    
    # O'z / O't / O'r / O'q / O'quv
    (r"\boz\b", "o'z"),
    (r"\bozaro\b", "o'zaro"),
    (r"\bozini\b", "o'zini"),
    (r"\boziga\b", "o'ziga"),
    (r"\bozining\b", "o'zining"),
    (r"\bozidan\b", "o'zidan"),
    (r"\bozida\b", "o'zida"),
    (r"\bozlari\b", "o'zlari"),
    (r"\bozgarish\b", "o'zgarish"),
    (r"\bozgartirish\b", "o'zgartirish"),
    (r"\bozgarmas\b", "o'zgarmas"),
    (r"\bozgardi\b", "o'zgardi"),
    (r"\bozgartirildi\b", "o'zgartirildi"),
    (r"\bornatish\b", "o'rnatish"),
    (r"\bornatilgan\b", "o'rnatilgan"),
    (r"\bornatildi\b", "o'rnatildi"),
    (r"\borniga\b", "o'rniga"),
    (r"\borin\b", "o'rin"),
    (r"\borinlar\b", "o'rinlar"),
    (r"\borganish\b", "o'rganish"),
    (r"\borganamiz\b", "o'rganamiz"),
    (r"\borganilmoqda\b", "o'rganilmoqda"),
    (r"\borganildi\b", "o'rganildi"),
    (r"\borta\b", "o'rta"),
    (r"\bortasida\b", "o'rtasida"),
    (r"\bortacha\b", "o'rtacha"),
    (r"\bortasidagi\b", "o'rtasidagi"),
    (r"\botkazish\b", "o'tkazish"),
    (r"\botkazildi\b", "o'tkazildi"),
    (r"\botkaziladi\b", "o'tkaziladi"),
    (r"\botkazilgan\b", "o'tkazilgan"),
    (r"\botkazilishi\b", "o'tkazilishi"),
    (r"\botish\b", "o'tish"),
    (r"\botgan\b", "o'tgan"),
    (r"\botadi\b", "o'tadi"),
    (r"\botib\b", "o'tib"),
    (r"\botmish\b", "o'tmish"),
    (r"\botkirligi\b", "o'tkirligi"),
    (r"\botmas\b", "o'tmas"),
    (r"\boxshash\b", "o'xshash"),
    (r"\boxshaydi\b", "o'xshaydi"),
    (r"\boxshamaydi\b", "o'xshamaydi"),
    (r"\boxshamaydigan\b", "o'xshamaydigan"),
    (r"\boxshatish\b", "o'xshatish"),
    (r"\bosish\b", "o'sish"),
    (r"\bosishi\b", "o'sishi"),
    (r"\bosmoqda\b", "o'smoqda"),
    (r"\bosgan\b", "o'sgan"),
    (r"\bosadi\b", "o'sadi"),
    (r"\bolchov\b", "o'lchov"),
    (r"\bolchash\b", "o'lchash"),
    (r"\bolchami\b", "o'lchami"),
    (r"\bolchamlari\b", "o'lchamlari"),
    (r"\bolcham\b", "o'lcham"),
    (r"\bolchandi\b", "o'lchandi"),
    (r"\boqish\b", "o'qish"),
    (r"\boqituvchi\b", "o'qituvchi"),
    (r"\boqitish\b", "o'qitish"),
    (r"\boquv\b", "o'quv"),
    (r"\boquvchi\b", "o'quvchi"),
    (r"\boqiladi\b", "o'qiladi"),
    (r"\boqigan\b", "o'qigan"),
    (r"\boqildi\b", "o'qildi"),
    (r"\bong\b", "o'ng"),
    (r"\bongi\b", "o'ngi"),
    (r"\bongda\b", "o'ngda"),
    (r"\bolim\b", "o'lim"),
    (r"\bolgan\b", "o'lgan"),
    (r"\bolik\b", "o'lik"),
    (r"\boyin\b", "o'yin"),
    (r"\boyinlar\b", "o'yinlar"),
    (r"\boynaydi\b", "o'ynaydi"),
    (r"\boylangan\b", "o'ylangan"),
    (r"\boylash\b", "o'ylash"),
    (r"\boylayman\b", "o'ylayman"),
    (r"\boylab\b", "o'ylab"),
    (r"\boylar\b", "o'ylar"),
    (r"\bochirildi\b", "o'chirildi"),
    (r"\bochirish\b", "o'chirish"),
    (r"\bochirib\b", "o'chirib"),
    (r"\bochir\b", "o'chir"),
    (r"\bopka\b", "o'pka"),
    (r"\bogri\b", "o'g'ri"),
    (r"\bogrilik\b", "o'g'rilik"),
    (r"\bogil\b", "o'g'il"),
    (r"\boglim\b", "o'g'lim"),
    (r"\bogliga\b", "o'g'liga"),
    (r"\boksuv\b", "o'ksuv"),
    (r"\bot\b", "o't"),
    
    # Tutuq belgili so'zlar (Arabiy / Mustaqil fonetik tutuq)
    (r"\btaminlash\b", "ta'minlash"),
    (r"\btaminlaydi\b", "ta'minlaydi"),
    (r"\btaminlandi\b", "ta'minlandi"),
    (r"\btaminlangan\b", "ta'minlangan"),
    (r"\btaminoti\b", "ta'minoti"),
    (r"\btaminlanadi\b", "ta'minlanadi"),
    (r"\bmalumot\b", "ma'lumot"),
    (r"\bmalumotlar\b", "ma'lumotlar"),
    (r"\bmalumotlarni\b", "ma'lumotlarni"),
    (r"\bmalumotlarga\b", "ma'lumotlarga"),
    (r"\bmalumotlardan\b", "ma'lumotlardan"),
    (r"\bmalumotining\b", "ma'lumotining"),
    (r"\bmalum\b", "ma'lum"),
    (r"\betibor\b", "e'tibor"),
    (r"\betiborni\b", "e'tiborni"),
    (r"\betiborga\b", "e'tiborga"),
    (r"\betiboringiz\b", "e'tiboringiz"),
    (r"\betiborli\b", "e'tiborli"),
    (r"\betiborsiz\b", "e'tiborsiz"),
    (r"\betirof\b", "e'tirof"),
    (r"\betiqod\b", "e'tiqod"),
    (r"\bsanat\b", "san'at"),
    (r"\bsanatkor\b", "san'atkor"),
    (r"\bsanati\b", "san'ati"),
    (r"\btasir\b", "ta'sir"),
    (r"\btasiri\b", "ta'siri"),
    (r"\btasirchan\b", "ta'sirchan"),
    (r"\btasirlanadi\b", "ta'sirlanadi"),
    (r"\btalim\b", "ta'lim"),
    (r"\btalimiy\b", "ta'limiy"),
    (r"\bmanaviy\b", "ma'naviy"),
    (r"\bmanaviyat\b", "ma'naviyat"),
    (r"\bmanaviyatsiz\b", "ma'naviyatsiz"),
    (r"\bmasul\b", "mas'ul"),
    (r"\bmasuliyat\b", "mas'uliyat"),
    (r"\bmasuliyatli\b", "mas'uliyatli"),
    (r"\bmeyor\b", "me'yor"),
    (r"\bmeyorlar\b", "me'yorlar"),
    (r"\bmeyorlarga\b", "me'yorlarga"),
    (r"\bmeyoriy\b", "me'yoriy"),
    (r"\bqatiy\b", "qat'iy"),
    (r"\bqatiyan\b", "qat'iyan"),
    (r"\bqatiylik\b", "qat'iylik"),
    (r"\belon\b", "e'lon"),
    (r"\belonlar\b", "e'lonlar"),
    (r"\beloniga\b", "e'loniga"),
    (r"\bmojiza\b", "mo'jiza"),
    (r"\bmojizaviy\b", "mo'jizaviy"),
    (r"\bmojizakor\b", "mo'jizakor"),
    (r"\bmarifat\b", "ma'rifat"),
    (r"\bmarifiy\b", "ma'rifiy"),
    (r"\bmaruza\b", "ma'ruza"),
    (r"\bmaruzalar\b", "ma'ruzalar"),
    (r"\bmaruzachi\b", "ma'ruzachi"),
    (r"\bmanoli\b", "ma'noli"),
    (r"\bmanosi\b", "ma'nosi"),
    (r"\bmano\b", "ma'no"),
    (r"\bmanolar\b", "ma'nolar"),
    (r"\btasis\b", "ta'sis"),
    (r"\btasischisi\b", "ta'sischisi"),
    (r"\btaziyq\b", "tazyiq"),
    (r"\btazim\b", "ta'zim"),
    (r"\btaqiq\b", "taqiq"),
    (r"\btaqiqlanadi\b", "taqiqlanadi"),
    (r"\btatbiq\b", "tatbiq"),
    (r"\btatbiqi\b", "tatbiqi"),
    (r"\bshariat\b", "shari'at"),
    (r"\bmasum\b", "ma'sum"),
    (r"\bshon\b", "shon"),
    (r"\bsher\b", "she'r"),
    (r"\bsherlar\b", "she'rlar"),
    (r"\bsheriyat\b", "she'riyat"),
    (r"\bsheriy\b", "she'riy"),
    (r"\bmashum\b", "mash'um"),
    (r"\bquron\b", "Qur'on"),
]

def restore_orthography(text: str) -> str:
    """
    Matndagi barcha o', g' va tutuq belgilarini 100% tiklaydi,
    Whisper buzgan so'zlarni to'g'rilaydi.
    """
    t = text
    t = unicodedata.normalize("NFC", t)
    t = re.sub(r"[`'ʻʼʽ՚’‘]", "'", t)
    
    for pat, rep in ASR_CORRECTIONS:
        t = re.sub(pat, rep, t, flags=re.IGNORECASE)
        
    for pat, rep in ORTHOGRAPHY_RULES:
        t = re.sub(pat, rep, t, flags=re.IGNORECASE)
        
    t = re.sub(r"o[']", "o'", t, flags=re.IGNORECASE)
    t = re.sub(r"g[']", "g'", t, flags=re.IGNORECASE)
    t = re.sub(r"'+", "'", t)
    t = re.sub(r"\s+", " ", t).strip()
    return t
